if(WIN32 OR APPLE)
    set(OBS_DEPS_VERSION "2026-06-25")
    list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/deps/obs-studio/cmake/finders")
    set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} CACHE PATH "CMake module search path" FORCE)
    if(WIN32)
        set(OBS_DEPS_PLATFORM "windows")
        set(OBS_DEPS_ARCH "x64")
        set(OBS_DEPS_EXTENSION "zip")
        set(OBS_DEPS_HASH "aea064cc550563d0095603385c22cc52b33de71e57ea3f6ff1ae1d54a0bb9d8a")
    elseif(APPLE)
        set(OBS_DEPS_PLATFORM "macos")
        set(OBS_DEPS_EXTENSION "tar.xz")
        if(CMAKE_OSX_ARCHITECTURES STREQUAL "arm64")
            set(OBS_DEPS_ARCH "arm64")
            set(OBS_DEPS_HASH "7cc91f62b1602708ce7cffaccd5dd5460677087784506db5aa9253bb513d0864")
        elseif(CMAKE_OSX_ARCHITECTURES STREQUAL "x86_64")
            set(OBS_DEPS_ARCH "x86_64")
            set(OBS_DEPS_HASH "6496d8f9b0080ed15c8c86cc989fe1ed50b2487b94d1b916b2b154089fdb7a5d")
        else()
            message(FATAL_ERROR "CMAKE_OSX_ARCHITECTURES must be either 'arm64' or 'x86_64'")
        endif()
    endif()

    set(OBS_DEPS_FILENAME "${OBS_DEPS_PLATFORM}-deps-${OBS_DEPS_VERSION}-${OBS_DEPS_ARCH}.${OBS_DEPS_EXTENSION}")
    set(OBS_DEPS_URL "https://github.com/obsproject/obs-deps/releases/download/${OBS_DEPS_VERSION}/${OBS_DEPS_FILENAME}")

    if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/deps/${OBS_DEPS_FILENAME}")
        message(STATUS "Downloading obs-deps from: ${OBS_DEPS_URL}")
        file(DOWNLOAD "${OBS_DEPS_URL}" "${CMAKE_CURRENT_SOURCE_DIR}/deps/${OBS_DEPS_FILENAME}" STATUS DOWNLOAD_STATUS EXPECTED_HASH SHA256=${OBS_DEPS_HASH})
        list(GET DOWNLOAD_STATUS 0 DOWNLOAD_ERRC)
        if(DOWNLOAD_ERRC GREATER 0)
            list(GET DOWNLOAD_STATUS 1 DOWNLOAD_ERRMSG)
            message(FATAL_ERROR "Failed to download ${OBS_DEPS_URL}: ${DOWNLOAD_ERRMSG}")
        endif()
    endif()

    file(ARCHIVE_EXTRACT INPUT "${CMAKE_CURRENT_SOURCE_DIR}/deps/${OBS_DEPS_FILENAME}" DESTINATION "${CMAKE_CURRENT_SOURCE_DIR}/deps/obs-deps")

    list(APPEND CMAKE_PREFIX_PATH "${CMAKE_CURRENT_SOURCE_DIR}/deps/obs-deps")
    set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} CACHE PATH "CMake prefix search path" FORCE)
endif()