include("${CMAKE_CURRENT_SOURCE_DIR}/cmake/package_common.cmake")

set(CPACK_PACKAGE_FILE_NAME "Waveform_v${WAVEFORM_VERSION}_Ubuntu_x64")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Devin Davila <daviladsoftware@gmail.com>")

set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

set(CPACK_INSTALL_DEFAULT_DIRECTORY_PERMISSIONS
    OWNER_READ OWNER_WRITE OWNER_EXECUTE
    GROUP_READ GROUP_EXECUTE
    WORLD_READ WORLD_EXECUTE
)

set(CPACK_GENERATOR "DEB")
include(CPack)