set(CPACK_PACKAGE_VERSION ${WAVEFORM_VERSION})

set(CPACK_PACKAGE_NAME "Waveform")
set(CPACK_PACKAGE_VENDOR "Phandasm")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Audio visualization plugin for OBS")
set(CPACK_COMPONENTS_ALL "waveform")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/installer/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/installer/README.txt")

set(CPACK_INSTALL_DEFAULT_DIRECTORY_PERMISSIONS
    OWNER_READ OWNER_WRITE OWNER_EXECUTE
    GROUP_READ GROUP_EXECUTE
    WORLD_READ WORLD_EXECUTE
)
