set(CPACK_PACKAGE_VERSION ${WAVEFORM_VERSION})

set(CPACK_PACKAGE_NAME "Waveform")
set(CPACK_PACKAGE_VENDOR "Phandasm")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Audio visualization plugin for OBS")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
