name: 'Mac/Linux/Windows CI'

on:
  push:
    paths-ignore: ['**.md']
  
  pull_request:
    paths-ignore: ['**.md']
  
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish Release'
        required: true
        type: boolean
      tagname:
        description: 'Tag Name'
        required: false
        type: string

jobs:
  windowsx64:
    name: 'Windows x64'
    runs-on: windows-2025-vs2026
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v7
        with:
          submodules: recursive
      
      - name: 'Checkout obs-studio'
        uses: actions/checkout@v7
        with:
          repository: 'obsproject/obs-studio'
          submodules: recursive
          path: 'deps/obs-studio'
          ref: '32.1.2'
      
      - name: 'OBS Cmake'
        run: cmake -S ${{github.workspace}}/deps/obs-studio -B ${{github.workspace}}/deps/obs-studio/build -A x64 -G "Visual Studio 18 2026" -DENABLE_FRONTEND=OFF -DENABLE_SCRIPTING=OFF -DENABLE_PLUGINS=OFF -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/deps/obs_install"
      
      - name: 'OBS Build'
        run: |
          cmake --build ${{github.workspace}}/deps/obs-studio/build --target obs-frontend-api --config Release
          cmake --install ${{github.workspace}}/deps/obs-studio/build --component Development --config Release
      
      - name: 'Cmake'
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -A x64 -G "Visual Studio 18 2026" -DSTATIC_RUNTIME=ON -DEXTRA_OPTIMIZATIONS=ON -DCI_BUILD=ON -DCMAKE_PREFIX_PATH="${{github.workspace}}/deps/obs-studio/build/libobs;${{github.workspace}}/deps/obs-studio/build/deps/w32-pthreads;${{github.workspace}}/deps/obs_install"
      
      - name: 'Build'
        run: |
          cmake --build ${{github.workspace}}/build --config Release
          cmake --install ${{github.workspace}}/build --config Release
      
      - name: 'Package'
        if: success() && ((github.ref_type == 'tag') || (github.event_name == 'workflow_dispatch')) && github.event_name != 'pull_request'
        run: |
          iscc.exe /O"${{github.workspace}}/installer" "${{github.workspace}}/installer/installer.iss"
          7z.exe a -r -y -tzip -mx9 "${{github.workspace}}/installer/Waveform_${{github.ref_name}}_Windows_x86_64.zip" "${{github.workspace}}/installer/bin/*"
      
      - name: 'Upload'
        if: success() && ((github.ref_type == 'tag') || (github.event_name == 'workflow_dispatch')) && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: Waveform_${{github.ref_name}}_Windows_x64
          path: |
            ${{github.workspace}}/installer/Waveform_v*_setup.exe
            ${{github.workspace}}/installer/Waveform_*_Windows_x86_64.zip

  macosarm64:
    name: 'MacOS Arm64'
    runs-on: macos-26
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v7
        with:
          submodules: recursive
      
      - name: 'Checkout obs-studio'
        uses: actions/checkout@v7
        with:
          repository: 'obsproject/obs-studio'
          submodules: recursive
          path: 'deps/obs-studio'
          ref: '32.1.2'
          fetch-depth: 0
      
      - name: 'Cherry-pick swift fix'
        run: git -C ${{github.workspace}}/deps/obs-studio cherry-pick b8f7a1e3b863b31b72898a8c01722d70772719ad

      - name: 'OBS Cmake'
        run: cmake -S ${{github.workspace}}/deps/obs-studio -B ${{github.workspace}}/deps/obs-studio/build -G Xcode -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DENABLE_FRONTEND=OFF -DENABLE_SCRIPTING=OFF -DENABLE_PLUGINS=OFF -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/deps/obs_install"
      
      - name: 'OBS Build'
        run: |
          cmake --build ${{github.workspace}}/deps/obs-studio/build --target obs-frontend-api --config RelWithDebInfo
          cmake --install ${{github.workspace}}/deps/obs-studio/build --component Development --config RelWithDebInfo
      
      - name: 'Cmake'
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G Xcode -DCI_BUILD=ON -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 -DCMAKE_OSX_ARCHITECTURES="arm64" -DMAKE_BUNDLE=ON -DENABLE_X86_SIMD=OFF -DBUILTIN_FFTW=ON -DCMAKE_PREFIX_PATH="${{github.workspace}}/deps/obs_install;${{github.workspace}}/deps/obs-studio/build/libobs" -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/bin"
      
      - name: 'Build'
        run: |
          cmake --build ${{github.workspace}}/build --config RelWithDebInfo
          cmake --install ${{github.workspace}}/build --config RelWithDebInfo
      
      - name: 'Package'
        if: success() && ((github.ref_type == 'tag') || (github.event_name == 'workflow_dispatch')) && github.event_name != 'pull_request'
        run: cmake --build ${{github.workspace}}/build --config RelWithDebInfo --target package
      
      - name: 'Upload'
        if: success() && ((github.ref_type == 'tag') || (github.event_name == 'workflow_dispatch')) && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: Waveform_${{github.ref_name}}_MacOS_arm64
          path: ${{github.workspace}}/build/*.pkg

  macosx64:
    name: 'MacOS x64'
    runs-on: macos-26
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v7
        with:
          submodules: recursive
      
      - name: 'Checkout obs-studio'
        uses: actions/checkout@v7
        with:
          repository: 'obsproject/obs-studio'
          submodules: recursive
          path: 'deps/obs-studio'
          ref: '32.1.2'
          fetch-depth: 0
      
      - name: 'Cherry-pick swift fix'
        run: git -C ${{github.workspace}}/deps/obs-studio cherry-pick b8f7a1e3b863b31b72898a8c01722d70772719ad

      - name: 'OBS Cmake'
        run: cmake -S ${{github.workspace}}/deps/obs-studio -B ${{github.workspace}}/deps/obs-studio/build -G Xcode -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DENABLE_FRONTEND=OFF -DENABLE_SCRIPTING=OFF -DENABLE_PLUGINS=OFF -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/deps/obs_install"
      
      - name: 'OBS Build'
        run: |
          cmake --build ${{github.workspace}}/deps/obs-studio/build --target obs-frontend-api --config RelWithDebInfo
          cmake --install ${{github.workspace}}/deps/obs-studio/build --component Development --config RelWithDebInfo
      
      - name: 'Cmake'
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G Xcode -DCI_BUILD=ON -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 -DCMAKE_OSX_ARCHITECTURES="x86_64" -DMAKE_BUNDLE=ON -DBUILTIN_FFTW=ON -DCMAKE_PREFIX_PATH="${{github.workspace}}/deps/obs_install;${{github.workspace}}/deps/obs-studio/build/libobs" -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/bin"
      
      - name: 'Build'
        run: |
          cmake --build ${{github.workspace}}/build --config RelWithDebInfo
          cmake --install ${{github.workspace}}/build --config RelWithDebInfo
      
      - name: 'Package'
        if: success() && ((github.ref_type == 'tag') || (github.event_name == 'workflow_dispatch')) && github.event_name != 'pull_request'
        run: cmake --build ${{github.workspace}}/build --config RelWithDebInfo --target package
      
      - name: 'Upload'
        if: success() && ((github.ref_type == 'tag') || (github.event_name == 'workflow_dispatch')) && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: Waveform_${{github.ref_name}}_MacOS_x86_64
          path: ${{github.workspace}}/build/*.pkg

  ubuntux64:
    name: 'Ubuntu x64'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v7
        with:
          submodules: recursive
      
      - name: 'Install dependencies'
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y libobs-dev libfftw3-dev
      
      - name: 'Cmake'
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSTATIC_FFTW=ON -DMAKE_DEB=ON -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/bin"
      
      - name: 'Build'
        run: |
          cmake --build ${{github.workspace}}/build
          cmake --install ${{github.workspace}}/build
      
      - name: 'Package'
        if: success() && ((github.ref_type == 'tag') || (github.event_name == 'workflow_dispatch')) && github.event_name != 'pull_request'
        run: cmake --build ${{github.workspace}}/build --target package
      
      - name: 'Upload'
        if: success() && ((github.ref_type == 'tag') || (github.event_name == 'workflow_dispatch')) && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: Waveform_${{github.ref_name}}_Ubuntu_x86_64
          path: ${{github.workspace}}/build/*.deb

  publish_release:
    if: ((github.ref_type == 'tag') || (inputs.publish == true)) && github.event_name != 'pull_request'
    needs: [macosarm64, macosx64, ubuntux64, windowsx64]
    name: 'Publish Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v7
      
      - name: 'Download artifacts'
        uses: actions/download-artifact@v8
        with:
          path: ${{github.workspace}}/artifacts

      - name: 'Publish'
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{github.workspace}}/artifacts/*/*.deb
            ${{github.workspace}}/artifacts/*/*.pkg
            ${{github.workspace}}/artifacts/*/*_setup.exe
            ${{github.workspace}}/artifacts/*/*_Windows_x86_64.zip
          body_path: ${{github.workspace}}/changelog.md
          tag_name: ${{inputs.publish && inputs.tagname || github.ref_name}}
          name: ${{inputs.publish && inputs.tagname || github.ref_name}}
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') }}
